### PR TITLE
Fixes IE9 stylesheets

### PR DESCRIPTION
**Pull request by andreslucena**
# What and why

Someone on Redmond (Washington) had the brilliant idea to limit the stylesheets size on 300 KB:
http://joshua.perina.com/africa/gambia/fajara/post/internet-explorer-css-file-size-limit

Also I can't find any official documentation about this on Microsoft website :(

The easy and quick solution I found to this problem is using Yet Another Gem: https://github.com/zweilove/css_splitter
# Steps to reproduce the bug
1. Open the website on IE9
2. There isn't any CSS loaded
# GIF tax

win95 was the best

### CODE REVIEW

**Comment by josepjaume** [comment]
Hey! Nice yet horrible finding! :D. Have you actually tried this on IE9?

**Comment by josepjaume** [comment]
Oh, I get it. So you had to hack your way into getting the CSS to load in IE9, just to make sure you can tell users to move on to a newer browser.

the surgeon s fw _de219d142a17300cc3e41416952c040d

**Comment by andreslucena** [comment]
Actually the alert style works without the CSS (at least what I've seen). 

I have tried this solution with a VM from modern.ie. Also I tried with IE10 and IE11 and it works fine. 

# Screenshots

## Before

captura de pantalla de 2016-03-04 09-28-21

## After

captura de pantalla de 2016-03-04 09-28-08

(The home top image isn't working but this doesn't matter at the moment)

**Comment by josepjaume** [comment]
:+1: then

**Pull request merged**
