### PR TITLE
Fix font awesome

### PR DESCRIPTION
**Pull request by josepjaume**

### CODE REVIEW

**Comment by beagleknight** [comment]
I hate "asset" gems but :+1:

**Comment by josepjaume** [comment]
We could use bower or node for that eh?

**Comment by josepjaume** [comment]
Let's merge this for now as it's quite urgent, but we can think about an asset management alternative in the future.

**Comment by beagleknight** [comment]
Yeah ofc :smile: . I usually manage those kind of assets using Gulp.

**Pull request merged**
