### PR TITLE
Add audio support for simple captcha

### PR DESCRIPTION
**Pull request by beagleknight**
I used this https://github.com/vinsol/simple-audio-captcha to add audio support to our current captcha. It works very well I think but the audio is in english. I'm not sure if it has multilanguage support.

It needs `espeak` and `lame` (lol XD) as dependencies. I have included both of them in our docker image.

### CODE REVIEW

**Comment by beagleknight** [comment]
Well.. multi-language support is available but it's using a value of SimpleCaptcha configuration: 
https://github.com/vinsol/simple-audio-captcha/blob/master/lib/simple_audio_captcha/audio_helpers.rb

We could fork the gem and add support to change this param dynamicallly but I'm not sure if it's worth. We can set catalan language by default.

**Comment by josepjaume** [comment]
Good job, but if we go this way, we should definitely fork the gem and add support for i18n.

That said, I personally prefer services like `reCaptcha`, even if they're not open source.

**Comment by josepjaume** [comment]
Closing this for now so we don't add noise.

**Comment by markets** [comment]
ei @josepjaume, que en penses sobre integrar algo similar a https://github.com/markets/invisible_captcha ? Normalment els honeypots funcionen prou bé en sites sense un tràfic hardcore, i el sign up ja no depèn de serveis de tercers, a més de temes d'accessibilitat ...

**Pull request closed without merging**
