### PR TITLE
Design: Home

### PR DESCRIPTION
**Pull request by josepjaume**
This implements the design on the home page.

### CODE REVIEW

**Comment by beagleknight** [comment]
Good job! :+1:

**Comment by xabier** [comment]
yes indeed!!!

;-)

On 28/01/16 14:45, David Morcillo wrote:

> Good job! :+1:
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AjuntamentdeBarcelona/decidimbcn/pull/106#issuecomment-176190821.

## 

wget -O - http://sindominio.net/~xabier/xabier.gpg.asc | gpg --import

```
               xabier BARANDIARAN   |  http://www.barandiaran.net
```

"There is no need for fear or hope, but only to look for new weapons"
                                                              DELEUZE

**Comment by josepjaume** [comment]
Hi @xabier :wave: :wave:  :smile:

**Comment by josepjaume** [comment]
Self-approve!

**Pull request merged**
