### PR TITLE
Add dataviz

### PR DESCRIPTION
**Pull request by josepjaume**
## What & Why?

This adds data visualizations related to the PAM process to the platform.
## How to QA?

A new "Data visualizations" menu element should appear.

### CODE REVIEW

**Comment by andreslucena** [comment]
A couple of changes: 
- [x] Remove the TOC (Table Of Contents) from Relat tab (the `div#index`) 
- [x] Change the separation line on sections:

`.slide { border-top: 2px solid lightgray; }`

**Comment by arnaumonty** [comment]
Change secondary menu names:
- [x] Replace "Relat" for "Resum del procés
- [x] Repalce "Interaccions totals" for "Xarxa d'interaccions"
- [x] Review the language in "Relat" page and the relation with language configuration of browser.
- [x] Show an alert in all dataviz pages with the following message: "Aquestes visualitzacions no es mostren correctament en dispositius mòbils"

**Comment by arnaumonty** [comment]
Change secondary menu names:

- [ ] Replace "Relat" for "Resum del procés
- [ ] Repalce "Interaccions totals" for "Xarxa d'interaccions"

Review the language in "Relat" page and the relation with language configuration of browser.

Show an alert in all dataviz pages with the following message:

"Aquestes visualitzacions no es mostren correctament en dispositius mòbils"

**Comment by josepjaume** [comment]
@arnaumonty: All the items in the list are already completed. Did you post this comment by mistake?

**Comment by andreslucena** [comment]
There is an error with proposals and cites presencials: 
https://decidimbcn-pr-432.herokuapp.com/dataviz/proposals 

It's related with the d3 library: 

> ReferenceError: d3 is not defined

**Comment by josepjaume** [comment]
Uop! Caching must have fooled me.

On Jul 11 2016, at 11:54 am, Andrés Lucena &lt;notifications@github.com&gt;
wrote:  

> There is an error with proposals and cites presencials:  
>  [https://decidimbcn-pr-432.herokuapp.com/dataviz/proposals](https
://decidimbcn-
pr-432.herokuapp.com/dataviz/proposals&r=cmVwbHkrMDAwMWI0ODIzMGU0MjgzYjY1Zjk1ODNjNTlkMDE0M2M0ZTNlMmMxNzk4YzliMGRhOTJjZjAwMDAwMDAxMTM5YjJlYjg5MmExNjljZTA5OGZkN2JjQHJlcGx5LmdpdGh1Yi5jb20=)

>

> It's related with the d3 library:

>

>> ReferenceError: d3 is not defined

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/AjuntamentdeBarcelona/decidim.barcelona/pull/432#issuecomment-231690866&r=cmVwbHkrMDAwMWI0ODIzMGU0MjgzYjY1Zjk1ODNjNTlkMDE0M2M0ZTNlMmMxNzk4YzliMGRhOTJjZjAwMDAwMDAxMTM5YjJlYjg5MmExNjljZTA5OGZkN2JjQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAG0gvafxeHgJ3gJgYgM0JI0bsdG3WNRks5qUhK4gaJpZM4I2Wso&r=cmVwbHkrMDAwMWI0ODIzMGU0MjgzYjY1Zjk1ODNjNTlkMDE0M2M0ZTNlMmMxNzk4YzliMGRhOTJjZjAwMDAwMDAxMTM5YjJlYjg5MmExNjljZTA5OGZkN2JjQHJlcGx5LmdpdGh1Yi5jb20=).

**Comment by andreslucena** [comment]
Right now the sunburst iframes (proposals and meetings) doesn't look so good, with the last changes on responsive. It does look good if the height is 600px or so. On these visualizations we can remove the mobile responsive alert box (.mobile-devices-alert).

**Pull request merged**
