### PR TITLE
Modify header of proposals page

### PR DESCRIPTION
**Pull request by beagleknight**
# What and why

Related to the issue #323 (I don't remember how to promote it to a PR so I created a new one).
# QA

Visit proposals page and interact with the header tabs.
# GIF Tax

# TODOs
- [x] Remove current filter options
- [x] Add new tabs filter
- [x] Clear options filter whenever a tab is selected
- [x] Preserve tab selection when a option is checked
- [x] Tests
- [x] Unregister subscribers
- [x] Fix "from meetings" filter
- [ ] @josepjaume CSS Magic tricks

### CODE REVIEW

**Comment by beagleknight** [comment]
@josepjaume I'm done with this task for now. I included a class to handle the global state between both filters. I haven't modified the meetings part so the two services will be available for now.
I'm not a huge fan of global instances but I think it's a good solution for now. Also I have decoupled the service from the components (no more `setState` in the service code) hence the name `FilterService` instead of `FilterComponentService`.

**Comment by josepjaume** [comment]
Sounds about right. Next step: Everything is `react` so we can remove this kind of cruft :+1: 

Nice styles, BTW!

**Comment by beagleknight** [comment]
haha don't mock me XD I have my own limits! You are right about full react. That will be awesome!

**Comment by beagleknight** [comment]
Ouch, @josepjaume I just realized there is a small bug. The crappy subscription system is performing double requests. I'm going to fix it asap and create another PR.

**Pull request merged**
