### PR TITLE
Add polymorphic comments component

### PR DESCRIPTION
**Pull request by beagleknight**
# What and why

In this PR I have successfully replaced the old comments server-side views with different React components and new API endpoints.

These components will be reusable across the application and used as a foundation to real time comments time to time.

The comments API is polymorphic so it needs a `commentable[type]` eg Proposal and a `commentable[id]`. Some endpoints uses just the comment id.
# QA

Checkout the branch and try to add new comments to a proposal.
# GIF Tax

# TODOs
- [x] Fix tests
- [x] As admin and as moderator
- [x] Administrator and moderator actions
- [x] Proposal's show meta tags (`react-helmet`)
- [x] Order selector
- [x] Comments title counters
- [x] Show log in warning for new comments
- [x] Notifications :(

### CODE REVIEW

**Comment by josepjaume** [comment]
C'mon buddy, you nearly have it!

**Comment by beagleknight** [comment]
@josepjaume need da thumbs! :)

**Comment by josepjaume** [comment]
Outstanding work!!!

I would give you THE THUMBZ _but_ I think this PR should come with a lot of deleted code - CommentsController, helpers, views, etc, since we're not using them anymore.

What do you think?

**Comment by beagleknight** [comment]
@josepjaume I created another PR using the same components for Debates. In that PR I cleaned all the stuff :+1:

**Pull request merged**
